services:
  mysql:
    image: mysql:8.0
    container_name: stagess_dev
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dev_db
      - MYSQL_USER=devuser
      - MYSQL_PASSWORD=devpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - network

volumes:
  mysql_data:


networks:
  network:
